#ifndef __EEPROM_WL_VOL_CFG_H__
#define __EEPROM_WL_VOL_CFG_H__

#define HAL_LIB_CFG_EEPROM_SIMULATED_SIZE		(1024U)

//Volume 0 config
#define HAL_LIB_CFG_EEPROM_WL_VOLUME0			(0U)
#define HAL_LIB_CFG_EEPROM_WL_VOLUME0_SIZE		(256U)
#define HAL_LIB_CFG_EEPROM_WL_VOLUME0_WL_FACTOR (1U)

//Volume 1 config
#define HAL_LIB_CFG_EEPROM_WL_VOLUME1			(256U)
#define HAL_LIB_CFG_EEPROM_WL_VOLUME1_SIZE		(128U)
#define HAL_LIB_CFG_EEPROM_WL_VOLUME1_WL_FACTOR (2U)

//Volume 2 config
#define HAL_LIB_CFG_EEPROM_WL_VOLUME2			(384U)
#define HAL_LIB_CFG_EEPROM_WL_VOLUME2_SIZE		(128U)
#define HAL_LIB_CFG_EEPROM_WL_VOLUME2_WL_FACTOR (4U)

//Volume 3 config
#define HAL_LIB_CFG_EEPROM_WL_VOLUME3			(512U)
#define HAL_LIB_CFG_EEPROM_WL_VOLUME3_SIZE		(512U)
#define HAL_LIB_CFG_EEPROM_WL_VOLUME3_WL_FACTOR (4U)

#endif //__EEPROM_WL_VOL_CFG_H__
